### PR TITLE
Donation banner with regards to Wakashio ecological disaster

### PR DESCRIPTION
**Pull request by MrSunshyne**
A simple banner with a link to the donation page at the top of the page using the existing colour scheme. 

Kindly vet the text and update if needed.

**Desktop** : 
image

**Mobile** : 
image

### CODE REVIEW

**Review by arwinneil — APPROVED** [review]

**Comment by jochenkirstaetter** [comment]
Hi fellows,

That's a bit difficult... The changes cannot be applied.

**Review by jochenkirstaetter — COMMENTED** [review]
Great idea, however it's complicated...

**Comment by MrSunshyne** [comment]
Care to elaborate as to what's complicated @jochenkirstaetter ?

**Comment by jochenkirstaetter** [comment]
Hi,
Did you do a complete due diligence of the organisation behind the action?

Also, you could have gotten in touch with us prior to just putting a PR here. Literally no one on the Messenger chat had any idea of what you were posting on Friday morning shortly after midnight.

Happy to discuss further.

Cheers, JoKi

**Comment by jochenkirstaetter** [comment]
Hi @MrSunshyne 

Thought about it, and how this could work out.

First of all, it would have been nice that you reached out to me directly ahead of creating the PR or at least initiating the conversation and not just posting the link of the PR into a Messenger chat where I'm not even participating in, as already mentioned.

Next, we cannot simply endorse only a single organisation that is looking into crowdfunding to provide assistance for anyone that has been impacted by the oil spill. For each such organisation we are, let's say obliged, to check their handling and intentions in regards to funds hence my question regarding due diligence. Imagine we'd promote a fraudster?

Hence a possible solution could be to write an article on the MSCC website on the oil spill and enlist multiple organisations that are collecting funds for any kind of relief. Of course, each checked for proper practice and a clear disclaimer that our community is not affiliated with any of those organisations. That article would be linked in the banner at the top of the page.

That's kind of similar how we already handle open job positions with partners and supporters of the community.

Personally, I have no idea about who this in the PR linked organisation is and how genuine their activities are.

Regards, JoKi

**Comment by MrSunshyne** [comment]
It was discussed with the team during the organizers meeting, after which I sent the PR.

**Comment by jochenkirstaetter** [comment]
⚠ Clarification

The automatic deployment of this PR has been picked up by the CI/CD chain and deployed to the conference website due to a false configuration in the handling of triggers. This has been adjusted to avoid similar cases of unwanted deployments to the live website.

The matter had been discussed during the team meeting on Thursday evening, however the conversation had been in progress and on my side I did not actively participate in that part of the meeting due to other obligations towards our child. A few other participants were also not fully paying attention based on too much noise in the background, tiredness or other reasons. One of those persons of that group noticed the accidental deployment of the banner and asked about it. Hence the previous deployment has been reverted to restore the previous state of the website.

There had been no fault at @MrSunshyne side.
I couldn't recall that this had been a topic during the meeting on Thursday evening. Apologies for that.

As mentioned in previous comment(s), the idea and changes of placing a banner at the top of the website is good and a positive signal to act on. Based on modi operati of the MSCC shall not endorse a single organisation in that regards and therefore the suggestion was made to provide an article on the MSCC blog at www.mscc.mu and have the banner link to that article instead. There we can provide an "official" statement about the positioning of the MSCC towards the volunteers in the oil spill removal and a disclaimer that we are not affiliated with any those organisation(s).

When done accordingly this amended PR shall be merged into the code base and deployed to the conference website.

Cheers, JoKi

**Comment by ish-sookun** [comment]
Folks, I remember a discussion about donating to NGOs for every registration but I admit I missed the part where you guys discussed about putting the link on the website. My bad, I apologize for that. I can speak for Shelly as well, she probably dozed off when this was discussed.

So, yes indeed, you guys might have gotten the impression that we listened and agreed to putting the link but that's unfortunate. No one's to blame :)

**Pull request closed without merging**
